//      This is part of rustyrig-fw. https://github.com/pripyatautomations/rustyrig-fw
//
// Do not pay money for this, except donations to the project, if you wish to.
// The software is not for sale. It is freely available, always.
//
// Licensed under MIT license, if built without mongoose or GPL if built with.
/*
 * This file is autogenerated by buildconf, please do not edit it directly.
 * Please edit config/radio.config.json then re-run './buildconf.pl radio' to make changes.
 */
#if !defined(_config_h)
#define _config_h
#define VERSION "20261003.02"
#define VERSION_MAJOR 0x135288b
#define VERSION_MINOR 0x2
#define HARDWARE "sb50"
#define EEPROM_TYPE_MMAP true
#undef EEPROM_TYPE_I2C
#define EEPROM_MMAP_ADDR 0x0000
#define RR_MAX_AMPS		2
#define RR_MAX_ATUS		4
#define RR_MAX_FILTERS		4
#define RF_TALK_TIMEOUT		300
#define MASTERDB_PATH "/var/lib/rustyrig/db/master.db"
#define MASTERDB_TEMPLATE "./sql/sqlite.master.sql"
#define USE_COREDUMPS_CLIENT
#define USE_COREDUMPS_FWDSP
#define DEBUG_BUILD
#define CAT_YAESU true
#define USE_GSTREAMER
#define USE_HTTP
#define USE_MQTT
#define USE_MONGOOSE
#define USE_OPUS
#define USE_FLAC
#define USE_SQLITE
#define USE_HAMLIB
#define BACKEND_HAMLIB_MODEL	2
#define BACKEND_HAMLIB_BAUD	38400
#define BACKEND_HAMLIB_PORT	"localhost:4532"
#define USE_PROFILING true
#define LOG_FILE "./radio-debug.log"
#define NOISY_EEPROM true
#define HTTP_AUTHDB_PATH	"./config/http.users"
#define EEPROM_SIZE 1048576
#define MAX_BANDS 10
#define HOST_EEPROM_FILE "build/radio/eeprom.bin"
#define HOST_CAT_PIPE "cat.fifo"
#define HOST_POSIX
#define HOST_LINUX	// This should not be here, but i2c depends on it for now
#define EEPROM_READONLY
//#define       NOISY_EEPROM true
#define BACKEND_HAMLIB_DEBUG    RIG_DEBUG_WARN
#define HTTP_USE_TLS            1
#define HTTP_TLS_KEY            "./config/key.pem"
#define HTTP_TLS_CERT           "./config/cert.pem"
#endif
